package com.appcoretech.expensemanager.models;

public enum ResponseCode {
	SUCCESS, ERROR, FAIL, ALREADY_EXISTS, DOEST_NOT_EXIST, INVALID_ACCESS_TOKEN, BAD_TOKEN, INVALID_CREDENTIAL, EXPIRED_TOKEN, VALIDATION_FAILED, NO_PERMISSION, NOT_VALID_APP
}
